### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by ASH1998** [zsdonghao/im2txt2im#1]
`n_images_train: 82783
tl : Build Image Embeddings = InceptionV3 + Dense Layer / uses SlimNetsLayer and DenseLayer instead
  tensorlayer:Instantiate InputLayer  input_image_layer: (64, 299, 299, 3)
  tensorlayer:Instantiate SlimNetsLayer InceptionV3: inception_v3
  tensorlayer:Instantiate DenseLayer  image_embedding: 512, identity
tl : Build Seq Embedding
     EmbeddingInputlayer
  tensorlayer:Instantiate EmbeddingInputlayer seq_embedding: (12000, 512)
tl : Build Model = image_embeddings + seq_embeddings + LSTMs + Dropout
     LSTM
  tensorlayer:Instantiate ReshapeLayer reshape_layer: (64, 1, 512)
Tensor("lstm/reshape_layer:0", shape=(64, 1, 512), dtype=float32)
  tensorlayer:Instantiate DynamicRNNLayer embed: n_hidden:512, in_dim:3 (64, 1, 512), cell_fn:BasicLSTMCell, dropout:None, n_layer:1
     batch_size (concurrent processes): 64
     n_params : 2
Traceback (most recent call last):
  File "train_im2txt2im_coco_64.py", line 871, in <module>
    tf.app.run()
  File "/home/gcloud1998/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_im2txt2im_coco_64.py", line 517, in main
    softmax, net_img_rnn, net_seq_rnn, state_feed = Build_Model(mode, net_image_embeddings, net_seq_embeddings, target_seqs=None, input_mask=None)
  File "/home/gcloud1998/Desktop/im2txt2im/model_im2txt.py", line 598, in Build_Model
    name = 'embed',
  File "/home/gcloud1998/Desktop/im2txt2im/tensorlayer/layers.py", line 3506, in __init__
    self.outputs = tf.reshape(tf.concat(1, outputs), [-1, n_hidden])
  File "/home/gcloud1998/.local/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1121, in concat
    dtype=dtypes.int32).get_shape().assert_is_compatible_with(
  File "/home/gcloud1998/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1048, in convert_to_tensor
    as_ref=False)
  File "/home/gcloud1998/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1144, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/gcloud1998/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 981, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype float32: 'Tensor("lstm/embed/rnn/transpose_1:0", shape=(64, 1, 512), dtype=float32)'`

**Comment by dany87kuo** [comment]
Hello,do you solve it?
